import { Companion, HotelLocation } from './types';

export const COMPANIONS: Companion[] = [
  {
    id: 'titli',
    name: 'Titli',
    tag: '# 550800',
    badge: 'DEMO',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=600',
    age: 22,
    height: "5'5\"",
    languages: ['English', 'Bengali'],
    specialty: 'High-Society Dinings & Executive Escapes',
    rate: 8000,
    city: 'Dhaka'
  },
  {
    id: 'fatiha',
    name: 'Fatiha',
    tag: '# 550963',
    badge: 'DEMO',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=600',
    age: 23,
    height: "5'6\"",
    languages: ['English', 'Bengali', 'Hindi'],
    specialty: 'Discreet In-Room Wellness & Aromatherapy',
    rate: 10000,
    city: 'Chittagong'
  },
  {
    id: 'ratri',
    name: 'Ratri',
    tag: '# 550856',
    badge: 'DEMO',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600',
    age: 21,
    height: "5'4\"",
    languages: ['English', 'Bengali'],
    specialty: 'Private Luxury Cruise & Yacht Companion',
    rate: 7500,
    city: 'Dhaka'
  },
  {
    id: 'nishat',
    name: 'Nishat',
    tag: '# 550125',
    badge: 'REGULAR',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=600',
    age: 22,
    height: "5'4\"",
    languages: ['English', 'Bengali'],
    specialty: 'Soothing Musical Gatherings & Fine Arts Companion',
    rate: 9000,
    city: 'Chittagong'
  },
  {
    id: 'nourin',
    name: 'Nourin',
    tag: '# 550100',
    badge: 'REGULAR',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=600',
    age: 23,
    height: "5'6\"",
    languages: ['English', 'Bengali'],
    specialty: 'High-Society Diners & Corporate Gala Hostess',
    rate: 9500,
    city: 'Dhaka'
  },
  {
    id: 'zara',
    name: 'Zara',
    tag: '# 550499',
    badge: 'REGULAR',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600',
    age: 22,
    height: "5'5\"",
    languages: ['English', 'Bengali', 'Hindi'],
    specialty: 'High-Profile Red-Carpet Gala Socialite',
    rate: 13000,
    city: 'Chittagong'
  },
  {
    id: 'maya',
    name: 'Maya',
    tag: '# 550711',
    badge: 'PREMIUM',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    age: 24,
    height: "5'7\"",
    languages: ['English', 'Bengali', 'French'],
    specialty: 'International Business Banquets & Gala Escort',
    rate: 15000,
    city: 'Dhaka'
  },
  {
    id: 'nila',
    name: 'Nila',
    tag: '# 550604',
    badge: 'ELITE',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600',
    age: 25,
    height: "5'8\"",
    languages: ['English', 'Bengali', 'Japanese'],
    specialty: 'Private Aviation Luxury Host & VIP Summit Liaison',
    rate: 20000,
    city: 'Dhaka',
    category: 'Female Model'
  },
  // MALE MODELS SEEDS
  {
    id: 'ayan',
    name: 'Ayan',
    tag: '# 770110',
    badge: 'REGULAR',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600',
    age: 25,
    height: "5'11\"",
    languages: ['English', 'Bengali'],
    specialty: 'Fitness Modeling, Grooming, and Executive Dinner Escort',
    rate: 6000,
    city: 'Dhaka',
    category: 'Male Model'
  },
  {
    id: 'zubair',
    name: 'Zubair',
    tag: '# 770240',
    badge: 'PREMIUM',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600',
    age: 26,
    height: "6'0\"",
    languages: ['English', 'Bengali', 'Hindi'],
    specialty: 'High-Fashion Liaison & Premium Secluded Corporate Gala Host',
    rate: 9000,
    city: 'Dhaka',
    category: 'Male Model'
  },
  // SPERM DONORS SEEDS
  {
    id: 'dr-mashiat',
    name: 'Dr. Mashiat',
    tag: '# 990112',
    badge: 'ELITE',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=600',
    age: 28,
    height: "5'10\"",
    languages: ['English', 'Bengali'],
    specialty: 'Dhaka Medical College Graduate, Golden pedigree, high IQ, healthy family history',
    rate: 25000,
    city: 'Dhaka',
    category: 'Sperm Donor',
    bloodGroup: 'O+ (Positive)',
    spermCount: '92 Million/ml (High Motility)'
  },
  {
    id: 'engr-tanvir',
    name: 'Engr. Tanvir',
    tag: '# 990234',
    badge: 'PREMIUM',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600',
    age: 27,
    height: "5'9\"",
    languages: ['English', 'Bengali'],
    specialty: 'BUET Software Engineer, high cognitive IQ testing (142), non-smoker, athletic medical tests cleared',
    rate: 18000,
    city: 'Chittagong',
    category: 'Sperm Donor',
    bloodGroup: 'A+ (Positive)',
    spermCount: '87 Million/ml (Excellent)'
  }
];

export const LOCATIONS: HotelLocation[] = [
  {
    id: 'le-meridien',
    name: 'Le Méridien Dhaka',
    star: '5 STAR',
    location: 'Dhaka',
    price: 9500,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600',
    description: 'Highly secure VIP checkout gates, premium luxury lounges, and complete anonymous elevator authentication systems.',
    distance: '3.2 km from Airport Terminal',
    address: 'Airport Road, Nikunja-2, Khilkhet, Dhaka 1229',
    checkInTime: '02:00 PM',
    checkOutTime: '12:00 PM',
    highlightedFacilities: 'Air Conditioning, Elevator Access, Premium Lounge, Indoor Pool, 24h Check-in, Valet Parking',
    room1Name: 'Premium Deluxe Twin',
    room1BedType: 'TWIN x 2',
    room1Capacity: 'Adult x 2, Child x 2',
    room1ViewType: 'no-view',
    room1Area: '18 sqm',
    room1Facilities: 'Breakfast Included, Non-Smoking room, Free cancellation',
    room1Price: 9500,
    room2Name: 'Presidential Executive Suite',
    room2BedType: 'KING x 1',
    room2Capacity: 'Adult x 2, Child x 2',
    room2ViewType: 'panoramic-skyline',
    room2Area: '25 sqm',
    room2Facilities: 'Executive Access, Free Gym, Breakfast Buffet Included',
    room2Price: 17500
  },
  {
    id: 'the-westin',
    name: 'The Westin Dhaka',
    star: '5 STAR',
    location: 'Dhaka',
    price: 11000,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
    description: 'Top-level premium penthouse spaces with high acoustic protection. Ideal for confidential business banquets and escapes.',
    distance: '1.1 km from Gulshan Circle-2',
    address: 'Plot 1, Road 45, Gulshan-2, Dhaka 1212',
    checkInTime: '02:00 PM',
    checkOutTime: '11:00 AM',
    highlightedFacilities: 'Air Conditioning, Skyline View, Keycard Security Lift, Gym & Spa, 24h Reception',
    room1Name: 'Deluxe Cozy Twin',
    room1BedType: 'TWIN x 2',
    room1Capacity: 'Adult x 2, Child x 1',
    room1ViewType: 'City View',
    room1Area: '20 sqm',
    room1Facilities: 'Free High-speed Wi-Fi, Coffee Maker, Free Cancel',
    room1Price: 11000,
    room2Name: 'Royal Club Suite',
    room2BedType: 'KING x 1',
    room2Capacity: 'Adult x 2, Child x 2',
    room2ViewType: 'Skyline View',
    room2Area: '32 sqm',
    room2Facilities: 'Club Lounge Butler, High-Security Escort Access, Free drinks',
    room2Price: 22000
  },
  {
    id: 'gulshan-secret',
    name: 'Gulshan Secret Suite (Safe House)',
    star: 'VIP SAFE HOUSE',
    location: 'Dhaka',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=600',
    description: 'Completely private discrete bodyTOUCH cozy flat sanctuary at the heart of Gulshan. Ultimate confidentiality, shielded with high-grade gated access protocols.',
    distance: 'Inside Gated Gulshan Residence',
    address: 'Road #79, Gulshan-2, Dhaka 1212',
    checkInTime: '01:00 PM',
    checkOutTime: '11:00 AM',
    highlightedFacilities: '100% Blind Safety, Gated Compound, Self Check-in, Acoustic Shielding, Ultra Confidential',
    room1Name: 'Standard Private Flatlet',
    room1BedType: 'KING x 1',
    room1Capacity: 'Adult x 2',
    room1ViewType: 'Garden-view',
    room1Area: '16 sqm',
    room1Facilities: 'Fully Furnished, Smart Lock, CCTV Protected Yard',
    room1Price: 5000,
    room2Name: 'Luxury Isolated Penthouse',
    room2BedType: 'KING x 1 + SOFA',
    room2Capacity: 'Adult x 3',
    room2ViewType: 'Confidential Blind View',
    room2Area: '30 sqm',
    room2Facilities: 'Private Backdoor Entry, Dedicated Exit Gate, High Isolation soundproofing',
    room2Price: 9000
  },
  {
    id: 'banani-cyber',
    name: 'Banani Cyber Penthouse (Safe House)',
    star: 'VIP SAFE HOUSE',
    location: 'Dhaka',
    price: 5500,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=600',
    description: 'Ultra-modern safe house penthouse setup in Banani. Panoramic city skyline view, private lift key card, and absolute electronic isolation.',
    distance: '0.5 km from Banani Lake',
    address: 'Road #11, Banani, Dhaka-1213',
    checkInTime: '02:00 PM',
    checkOutTime: '12:00 PM',
    highlightedFacilities: 'Acoustic Soundproofing, Smart Keypad, Isolated Elevator, Private Balcony, High-grade electronic shield',
    room1Name: 'Standard Cozy Studio',
    room1BedType: 'QUEEN x 1',
    room1Capacity: 'Adult x 2',
    room1ViewType: 'No View (Privacy)',
    room1Area: '15 sqm',
    room1Facilities: 'Premium Sound Proofing, High-Speed internet, self-kitchen',
    room1Price: 5500,
    room2Name: 'Cyber Presidential Studio',
    room2BedType: 'KING x 1',
    room2Capacity: 'Adult x 2, Child x 1',
    room2ViewType: 'Panoramic Skyline View',
    room2Area: '28 sqm',
    room2Facilities: 'Private Lift Entry, Secure Access Log clearance, Free Airport Cab',
    room2Price: 10500
  },
  {
    id: 'radisson',
    name: 'Radisson Blu Bay View',
    star: '5 STAR',
    location: 'Chittagong',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=600',
    description: 'Secluded luxury rooms with stunning coastal breeze. Strict guest-only authentication protocols to ensure zero disclosure.',
    distance: '4.5 km from Patenga Beach-line',
    address: 'SS Khaled Road, Lalkhan Bazar, Chittagong 4000',
    checkInTime: '02:00 PM',
    checkOutTime: '12:00 PM',
    highlightedFacilities: 'Air Conditioning, Bay View pool, Strict Confidentiality, Executive Butler service, Free Spa',
    room1Name: 'Coastal Twin Deluxe',
    room1BedType: 'TWIN x 2',
    room1Capacity: 'Adult x 2, Child x 1',
    room1ViewType: 'Hill Side View',
    room1Area: '22 sqm',
    room1Facilities: 'Breakfast buffet, Smart TV, Gym access',
    room1Price: 8500,
    room2Name: 'Bay View Royal Suite',
    room2BedType: 'KING x 1',
    room2Capacity: 'Adult x 2, Child x 2',
    room2ViewType: 'Panoramic Coastal View',
    room2Area: '36 sqm',
    room2Facilities: 'Dedicated Premium Lounge, Free massage session, High discrete security',
    room2Price: 15500
  }
];
